import { ConversionOption } from '../components/conversion-card/conversion-card.component';

export const CONVERSION_OPTIONS: ConversionOption[] = [
  {
    id: 'docx-pdf',
    title: 'DOCX to PDF',
    description: 'Convierte documentos Word a PDF',
    fromFormat: 'docx',
    toFormat: 'pdf',
    icon: 'document',
  },
  {
    id: 'pdf-docx',
    title: 'PDF to DOCX',
    description: 'Transforma PDFs en documentos Word editables',
    fromFormat: 'pdf',
    toFormat: 'docx',
    icon: 'document',
  },
  {
    id: 'html-pdf',
    title: 'HTML to PDF',
    description: 'Genera PDFs desde archivos HTML',
    fromFormat: 'html',
    toFormat: 'pdf',
    icon: 'code',
  },
  {
    id: 'docx-txt',
    title: 'DOCX to TXT',
    description: 'Extrae texto plano de documentos Word',
    fromFormat: 'docx',
    toFormat: 'txt',
    icon: 'document',
  },

  {
    id: 'xlsx-pdf',
    title: 'Excel to PDF',
    description: 'Convierte hojas de cálculo Excel a PDF',
    fromFormat: 'xlsx',
    toFormat: 'pdf',
    icon: 'document',
  },
  {
    id: 'pptx-pdf',
    title: 'PowerPoint to PDF',
    description: 'Convierte presentaciones a PDF',
    fromFormat: 'pptx',
    toFormat: 'pdf',
    icon: 'document',
  },


  {
    id: 'jpg-png',
    title: 'JPG to PNG',
    description: 'Convierte imágenes JPG a PNG',
    fromFormat: 'jpg',
    toFormat: 'png',
    icon: 'image',
  },
  {
    id: 'png-jpg',
    title: 'PNG to JPG',
    description: 'Convierte imágenes PNG a JPG',
    fromFormat: 'png',
    toFormat: 'jpg',
    icon: 'image',
  },
  {
    id: 'webp-png',
    title: 'WebP to PNG',
    description: 'Convierte imágenes WebP a PNG',
    fromFormat: 'webp',
    toFormat: 'png',
    icon: 'image',
  },
  {
    id: 'png-webp',
    title: 'PNG to WebP',
    description: 'Convierte imágenes PNG a WebP',
    fromFormat: 'png',
    toFormat: 'webp',
    icon: 'image',
  },
  {
    id: 'jpg-webp',
    title: 'JPG to WebP',
    description: 'Convierte imágenes JPG a WebP',
    fromFormat: 'jpg',
    toFormat: 'webp',
    icon: 'image',
  },
  {
    id: 'heic-jpg',
    title: 'HEIC to JPG',
    description: 'Convierte imágenes HEIC a JPG',
    fromFormat: 'heic',
    toFormat: 'jpg',
    icon: 'image',
  },

  {
    id: 'compress-pdf',
    title: 'Compress PDF',
    description: 'Reduce el tamaño de archivos PDF hasta 90%',
    fromFormat: 'pdf',
    toFormat: 'pdf',
    icon: 'compress',
  },
  {
    id: 'compress-jpg',
    title: 'Compress JPG',
    description: 'Optimiza imágenes JPG manteniendo calidad',
    fromFormat: 'jpg',
    toFormat: 'jpg',
    icon: 'compress',
  },
  {
    id: 'compress-png',
    title: 'Compress PNG',
    description: 'Reduce el tamaño de imágenes PNG',
    fromFormat: 'png',
    toFormat: 'png',
    icon: 'compress',
  },
];
