import { ConversionOption } from '../components/conversion-card/conversion-card.component';

export const CONVERSION_OPTIONS: ConversionOption[] = [
  {
    id: 'docx-pdf',
    title: 'DOCX to PDF',
    description: 'Convert Word documents to PDF',
    fromFormat: 'docx',
    toFormat: 'pdf',
    icon: 'document',
  },
  {
    id: 'pdf-docx',
    title: 'PDF to DOCX',
    description: 'Transform PDFs into editable Word documents',
    fromFormat: 'pdf',
    toFormat: 'docx',
    icon: 'document',
  },
  {
    id: 'html-pdf',
    title: 'HTML to PDF',
    description: 'Generate PDFs from HTML files',
    fromFormat: 'html',
    toFormat: 'pdf',
    icon: 'code',
  },
  {
    id: 'docx-txt',
    title: 'DOCX to TXT',
    description: 'Extract plain text from Word documents',
    fromFormat: 'docx',
    toFormat: 'txt',
    icon: 'document',
  },

  {
    id: 'xlsx-pdf',
    title: 'Excel to PDF',
    description: 'Convert Excel spreadsheets to PDF',
    fromFormat: 'xlsx',
    toFormat: 'pdf',
    icon: 'document',
  },
  {
    id: 'pptx-pdf',
    title: 'PowerPoint to PDF',
    description: 'Convert PowerPoint presentations to PDF',
    fromFormat: 'pptx',
    toFormat: 'pdf',
    icon: 'document',
  },


  {
    id: 'jpg-png',
    title: 'JPG to PNG',
    description: 'Convert JPG images to PNG',
    fromFormat: 'jpg',
    toFormat: 'png',
    icon: 'image',
  },
  {
    id: 'png-jpg',
    title: 'PNG to JPG',
    description: 'Convert PNG images to JPG',
    fromFormat: 'png',
    toFormat: 'jpg',
    icon: 'image',
  },
  {
    id: 'webp-png',
    title: 'WebP to PNG',
    description: 'Convert WebP images to PNG',
    fromFormat: 'webp',
    toFormat: 'png',
    icon: 'image',
  },
  {
    id: 'png-webp',
    title: 'PNG to WebP',
    description: 'Convert PNG images to WebP',
    fromFormat: 'png',
    toFormat: 'webp',
    icon: 'image',
  },
  {
    id: 'jpg-webp',
    title: 'JPG to WebP',
    description: 'Convert JPG images to WebP',
    fromFormat: 'jpg',
    toFormat: 'webp',
    icon: 'image',
  },
  {
    id: 'heic-jpg',
    title: 'HEIC to JPG',
    description: 'Convert HEIC images to JPG',
    fromFormat: 'heic',
    toFormat: 'jpg',
    icon: 'image',
  },

  {
    id: 'compress-pdf',
    title: 'Compress PDF',
    description: 'Reduce the size of PDF files by up to 90%',
    fromFormat: 'pdf',
    toFormat: 'pdf',
    icon: 'compress',
  },
  {
    id: 'compress-jpg',
    title: 'Compress JPG',
    description: 'Optimize JPG images while maintaining quality',
    fromFormat: 'jpg',
    toFormat: 'jpg',
    icon: 'compress',
  },
  {
    id: 'compress-png',
    title: 'Compress PNG',
    description: 'Reduce the size of PNG images effectively',
    fromFormat: 'png',
    toFormat: 'png',
    icon: 'compress',
  },
];
